# Generated by Django 4.0.5 on 2022-07-27 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boulangerie', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='date_order',
            field=models.DateField(blank=True, null=True, verbose_name='Date de commande'),
        ),
        migrations.AlterField(
            model_name='order',
            name='date_takeaway',
            field=models.DateField(blank=True, null=True, verbose_name="Date d'enlèvement"),
        ),
        migrations.AlterField(
            model_name='order',
            name='total_price',
            field=models.FloatField(blank=True, null=True, verbose_name='Prix total'),
        ),
        migrations.AlterField(
            model_name='order',
            name='total_quantity',
            field=models.FloatField(blank=True, null=True, verbose_name='Quantité total'),
        ),
    ]
